name: 定时运行IP脚本

on:
  schedule:
    # 定时任务时间（UTC时区），每天凌晨2点执行（对应北京时间10点）
    - cron: '0 2 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码仓库
        uses: actions/checkout@v4

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # 选择合适的Python版本

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests  # 脚本依赖requests库

      - name: 获取并运行脚本
        run: |
          # 下载脚本
          curl -O https://raw.githubusercontent.com/bogy4218/703/refs/heads/main/ip.py
          # 运行脚本
          python ip.py

      - name: 保存文件到仓库
        run: |
          # 假设生成的文件在当前目录下
          # 如果需要，调整源文件路径
          cp 需要保存的文件 ikuai_ipgroup-cn.txt
          
          # 配置Git
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # 添加文件并提交
          git add ikuai_ipgroup-cn.txt
          # 只有当文件有变化时才提交
          git diff --quiet && git diff --staged --quiet || git commit -m "Update ikuai_ipgroup-cn.txt"
          
          # 推送更改
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
