name: 定时运行IP脚本

on:
  schedule:
    # 定时任务时间（UTC时区），每天凌晨2点执行（对应北京时间10点）
    - cron: '0 2 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码仓库
        uses: actions/checkout@v4

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # 选择合适的Python版本

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests  # 脚本依赖requests库

      - name: 下载并运行脚本
        run: |
          # 下载脚本
          curl -O https://raw.githubusercontent.com/bogy4218/703/refs/heads/main/ip.py
          # 运行脚本
          python ip.py

      - name: 提交更改
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add ikuai_ipgroup-cn.txt
          git commit -m "Update IP list"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
